name: "My action"
description: "This is my action"

inputs:
  message:
    description: "Message to print"
    required: true
    default: "World"

runs:
  using: composite

  steps:
    - name: Hello World
      run: echo "Hello ${{ inputs.message }}"
      shell: bash