name: Test

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Mars"
