name: PUSH TEST

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: echo "Hello World"
      
    - name: Touch file
      run: touch hello.txt

    - name: set text
      run: echo "Hello World" >> hello.txt

    - name: read file
      run: cat hello.txt 

  other:
    needs: hello
    runs-on: ubuntu-latest
    steps:
    - name: LS
      run: ls -al